#!/usr/bin/env python3
"""
workforce_paths.py — read-shim and writer for the .workforce/ directory.

Existing projects keep orchestration artifacts at the root (e.g. ./vision.md,
./WORKFORCE.md). The new architecture writes them under .workforce/. To avoid
breaking mid-flight projects, we read from either location (preferring the
new one) and always write to the new one.

Public API
----------

    read(project_dir, name)        -> Optional[Path]
        Returns the first existing path for `name`, or None.

    write_path(project_dir, name)  -> Path
        Returns the canonical write location under .workforce/, creating
        parent directories. The caller writes the bytes.

    workforce_dir(project_dir)     -> Path
        Returns <project_dir>/.workforce/, creating it (with .gitignore) on
        first call.

    is_orchestration_artifact(name) -> bool
        Returns True if `name` belongs in .workforce/ (intent.md, dispatch.md,
        integration.md, alignment-report.md, runs/..., status/...).
        Engineer outputs (architecture.md, vision.md, ...) return False —
        those stay at project root.

Usage
-----

    from workforce_paths import read, write_path, is_orchestration_artifact

    intent = read(Path.cwd(), "intent.md")        # legacy path or .workforce/
    out = write_path(Path.cwd(), "dispatch.md")   # always .workforce/dispatch.md
    out.write_text("...")
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional


WORKFORCE_DIR_NAME = ".workforce"

# Names that always belong under .workforce/. Everything else (architecture.md,
# vision.md, brainstorm.md, etc.) stays at project root for back-compat.
ORCHESTRATION_ARTIFACTS = frozenset(
    {
        "intent.md",
        "dispatch.md",
        "integration.md",
        "alignment-report.md",
    }
)

# Path *prefixes* (relative to .workforce/) that are also orchestration-owned.
ORCHESTRATION_PREFIXES = (
    "runs/",
    "status/",
)

GITIGNORE_BODY = """\
# Auto-generated by scripts/workforce_paths.py
# Per-run logs and live status files are local-only.
runs/
status/
"""


def is_orchestration_artifact(name: str) -> bool:
    """True iff `name` belongs in .workforce/ rather than the project root."""
    if name in ORCHESTRATION_ARTIFACTS:
        return True
    return any(name.startswith(prefix) for prefix in ORCHESTRATION_PREFIXES)


def workforce_dir(project_dir: Path) -> Path:
    """Return .workforce/, creating it (with .gitignore) on first call."""
    project_dir = Path(project_dir).resolve()
    wf = project_dir / WORKFORCE_DIR_NAME
    if not wf.exists():
        wf.mkdir(parents=True, exist_ok=True)
        gitignore = wf / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(GITIGNORE_BODY)
    return wf


def write_path(project_dir: Path, name: str) -> Path:
    """Return the canonical write location for `name`.

    For orchestration artifacts: <project>/.workforce/<name>, with parents
    created. For everything else: <project>/<name>.
    """
    project_dir = Path(project_dir).resolve()
    if is_orchestration_artifact(name):
        target = workforce_dir(project_dir) / name
        target.parent.mkdir(parents=True, exist_ok=True)
        return target
    return project_dir / name


def read(project_dir: Path, name: str) -> Optional[Path]:
    """Resolve `name` to a real existing path, preferring .workforce/ over root.

    Returns None if neither location has the file. Callers handle the None
    case (typically: file doesn't exist yet, halt or prompt user).
    """
    project_dir = Path(project_dir).resolve()
    wf_path = project_dir / WORKFORCE_DIR_NAME / name
    if wf_path.exists():
        return wf_path
    root_path = project_dir / name
    if root_path.exists():
        return root_path
    return None


def main() -> None:
    """CLI for shell scripts and orchestrator agents.

    Usage:
        workforce_paths.py read <name>            # prints resolved path or '' if missing
        workforce_paths.py write-path <name>      # prints canonical write path (creates dirs)
        workforce_paths.py is-orchestration <name> # exit 0 if yes, 1 if no
    """
    import argparse
    import sys

    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--project-dir", default=".", help="Project root (default: cwd)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_read = sub.add_parser("read", help="Resolve a name to an existing path")
    p_read.add_argument("name")

    p_write = sub.add_parser("write-path", help="Canonical write path (creates dirs)")
    p_write.add_argument("name")

    p_is = sub.add_parser("is-orchestration", help="Exit 0 if name is orchestration artifact")
    p_is.add_argument("name")

    args = ap.parse_args()
    project_dir = Path(args.project_dir).resolve()

    if args.cmd == "read":
        path = read(project_dir, args.name)
        print(str(path) if path else "")
    elif args.cmd == "write-path":
        print(str(write_path(project_dir, args.name)))
    elif args.cmd == "is-orchestration":
        sys.exit(0 if is_orchestration_artifact(args.name) else 1)


if __name__ == "__main__":
    main()
